# permissions for end users to view vaultapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultapp-viewer-role
rules:
- apiGroups:
  - secretmanagement.falselypositive.com
  resources:
  - vaultapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secretmanagement.falselypositive.com
  resources:
  - vaultapps/status
  verbs:
  - get
