# permissions for end users to edit vaultapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultapp-editor-role
rules:
- apiGroups:
  - secretmanagement.falselypositive.com
  resources:
  - vaultapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secretmanagement.falselypositive.com
  resources:
  - vaultapps/status
  verbs:
  - get
