name: ci-demo

on:
  push:

jobs:
   hello-devsecops:
     runs-on: ubuntu-latest

     steps:
     - name: say hello
       run: echo "Hello bfs"
     - uses: actions/checkout@v3
     - name: echo file
       run: cat Makefile

   build-code:
     runs-on: ubuntu-latest
     needs:
       - hello-devsecops

     steps:
       - uses: actions/checkout@v3
       - name: build code
         run: go build

